# Ignore directories managed by Composer or generated by Magento
vendor/
generated/
var/

# Ignore Git directory
.git/

# Ignore node_modules if present
node_modules/

# Ignore IDE/editor specific files
.idea/
.vscode/

# Ignore environment files (should be mounted or managed securely)
.env
app/etc/env.php

